export default {
    title: "Why we build on EOSIO",
    p1: "Since the evolution of blockchain technology came to include smart contracts there have been many contenders. Ethereum, which was the first platform to provide smart contract functionality, still reigns as king with the most active dapps at well over 2,600. It also maintains a high token value, and high network worth. Bitcoin has by far the largest market cap, followed by Ethereum, and then EOS. For our purposes, we will be focusing on comparing smart contract platforms, and not digital assets like Bitcoin which are used as stores of value or for speculation.",
    h1: "Some basic comparisons",
    p2: "The EOS Mainnet, based on the EOSIO software released by Block.one, has been live now for 16 months and has seen a steady rise in new software available for users. What is really interesting, and speaks volumes about the future of the base technology is that the daily active users and the number of transactions successfully performed is constantly growing.",
    p3: "Let’s talk about why we at Scatter build primarily for EOSIO networks and why we think that if you are a developer interested in building a decentralized application it should be your primary choice.",
    h2: "EOS has a more active and engaged user base",
    p4: "There are more EOS users that use the platform on any given day, compared to any of the other leading smart contract platforms such as Ethereum or Tron.",
    h3: "EOS has by far the largest transaction volume",
    p5: "Because of the nature of the Delegated Proof of Stake consensus mechanism that EOSIO runs on, it can perform an order of magnitude more daily transactions over its nearest competitor, Ethereum. More transactions means more use by your users, which generally translates into higher profits for your project.",
    p6: "We have also added Bitcoin into this comparison chart, since it is the market leader, although it is not a smart contract platform and is performing the bare minimum when it comes to useful decentralized computation. EOS Mainnet far outstrips the competition, and this chart does not include sister and side chains like Telos, WORBLI, BOS, etc.",
    p7: "If you are a developer who wants users to perform a high volume of transactions on your decentralized application then EOSIO platforms are the clear choice.",
    h4: "Tooling, Developer learning curve, and Scatter",
    p8: "While development preferences are largely a subjective matter, we at Scatter believe that C++, which is a known quantity with decades of library support and documentation, is far superior to Solidity, which is the required language for creating smart contracts that run on Ethereum. This means that if you are a C++ developer, getting up and running quickly on EOS is straightforward, and does not require that you learn the quirks and intricacies of a new language along with all the other concepts required to develop a decentralized application.",
    p9: "Furthermore, the ever growing set of resources for starting from the floor and getting you up and running on EOS is quite remarkable. We highly recommend Peter Keay's free course on <a href='https://www.udemy.com/learning-blockchain-development-with-eos-and-cpp/'>Blockchain Smart Contract Development and Frontend Programming</a> as a way to learn the basics quickly. Ivan on Tech is also <a href='https://www.youtube.com/watch?v=PD0zS3C0ImQ'>producing a series</a> which holds your hand through the whole process.",
    p10: "At Scatter our core goal is to provide base technologies for developers and users to gain easy access to advanced blockchain networks.",
    p11: "We provide many of the core libraries that developers use to connect to partnered wallets, or to the network of their choice. <a href='https://github.com/GetScatter/scatter-js/'>ScatterJS</a> is particularly popular, being integrated into hundreds of EOS applications.",
    p12: "Getting Scatter technologies integrated into your dapp is a matter of just a few lines of code. If you have any questions there are almost always experienced <a href='https://t.me/ScatterDevelopers'>developers from the community available on Telegram</a> who are happy to help you get started.",
    p13: "We also provide Unity support through our <a href='https://github.com/GetScatter/scatter-sharp'>scatter-sharp</a> and <a href='https://github.com/GetScatter/eos-sharp'>eos-sharp</a> libraries and expect that as the adoption of EOSIO technologies grows, we will start seeing triple-A studios using it to connect their console games to blockchain networks.",
    h5: "References"
    
}